# Generated by Django 5.1.7 on 2025-12-29 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fallecido', models.IntegerField()),
                ('esterilizado', models.IntegerField()),
                ('adoptado_imusa', models.IntegerField()),
                ('es_peligroso', models.IntegerField()),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnimalColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'animal_color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('firma_ingreso', models.TextField(null=True)),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('hora_egreso', models.TimeField(blank=True, null=True)),
                ('firma_egreso', models.TextField(null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('finalizada', models.IntegerField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'atencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AtencionInsumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cant_ml', models.IntegerField(blank=True, null=True)),
                ('cant_ml_prequirurgico', models.IntegerField(blank=True, null=True)),
                ('cant_ml_induccion', models.IntegerField(blank=True, null=True)),
                ('cant_ml_quirofano', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atencion_insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'color',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=255)),
                ('codigo_calle', models.IntegerField(blank=True, null=True)),
                ('altura', models.IntegerField()),
                ('bis', models.IntegerField()),
                ('letra', models.CharField(blank=True, max_length=1, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('depto', models.CharField(blank=True, max_length=10, null=True)),
                ('monoblock', models.IntegerField(blank=True, null=True)),
                ('barrio', models.CharField(blank=True, max_length=255, null=True)),
                ('vecinal', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('seccional_policial', models.CharField(blank=True, max_length=255, null=True)),
                ('localidad', models.CharField(max_length=255)),
                ('lineas_tup', models.CharField(blank=True, max_length=500, null=True)),
                ('coordenada_x', models.CharField(blank=True, max_length=255, null=True)),
                ('coordenada_y', models.CharField(blank=True, max_length=255, null=True)),
                ('fraccion_censal', models.CharField(blank=True, max_length=255, null=True)),
                ('radio_censal', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'domicilio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Efector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('unidad_movil', models.IntegerField()),
            ],
            options={
                'db_table': 'efector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'especie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoEgreso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'estado_egreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tope_max', models.IntegerField(blank=True, null=True)),
                ('tope_min', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(blank=True, max_length=15, null=True)),
                ('firma', models.TextField(null=True)),
                ('legajo', models.IntegerField()),
            ],
            options={
                'db_table': 'personal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalEfector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'personal_efector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('es_peligrosa', models.IntegerField()),
            ],
            options={
                'db_table': 'raza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tamaño',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEfector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_efector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPersonal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tipo_personal',
                'managed': False,
            },
        ),
    ]
