# Generated by Django 5.1.7 on 2025-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id_animal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=1)),
                ('año_nacimiento', models.IntegerField()),
                ('pelaje_color', models.CharField(blank=True, max_length=255, null=True)),
                ('fallecido', models.IntegerField()),
            ],
            options={
                'db_table': 'animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id_atencion', models.AutoField(primary_key=True, serialize=False)),
                ('señas_particulares', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones_animal', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('hora_egreso', models.TimeField(blank=True, null=True)),
                ('estado_sanitario_egreso', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones_atencion', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'atencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AtencionInsumo',
            fields=[
                ('id_ate_ins', models.AutoField(primary_key=True, serialize=False)),
                ('cant_ml', models.IntegerField(blank=True, null=True)),
                ('cant_ml_prequirurgico', models.IntegerField(blank=True, null=True)),
                ('cant_ml_induccion', models.IntegerField(blank=True, null=True)),
                ('cant_ml_quirofano', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atencion_insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id_domicilio', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=255)),
                ('altura', models.IntegerField()),
                ('bis', models.IntegerField()),
                ('letra', models.CharField(blank=True, max_length=1, null=True)),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('depto', models.CharField(blank=True, max_length=10, null=True)),
                ('monoblock', models.IntegerField(blank=True, null=True)),
                ('barrio', models.CharField(blank=True, max_length=255, null=True)),
                ('vecinal', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('seccional_policial', models.CharField(blank=True, max_length=255, null=True)),
                ('localidad', models.CharField(max_length=255)),
                ('coordenada_x', models.CharField(blank=True, max_length=255, null=True)),
                ('coordenada_y', models.CharField(blank=True, max_length=255, null=True)),
                ('punto_x', models.CharField(blank=True, max_length=255, null=True)),
                ('punto_y', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.CharField(blank=True, max_length=255, null=True)),
                ('longitud', models.CharField(blank=True, max_length=255, null=True)),
                ('fraccion_censal', models.CharField(blank=True, max_length=255, null=True)),
                ('radio_censal', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'domicilio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Efector',
            fields=[
                ('id_efector', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('domicilio', models.CharField(max_length=255)),
                ('latitud', models.CharField(blank=True, max_length=255, null=True)),
                ('longitud', models.CharField(blank=True, max_length=255, null=True)),
                ('coordenadas', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('vecinal', models.CharField(blank=True, max_length=255, null=True)),
                ('punto_x', models.CharField(blank=True, max_length=255, null=True)),
                ('punto_y', models.CharField(blank=True, max_length=255, null=True)),
                ('lineas_tup', models.CharField(blank=True, max_length=500, null=True)),
                ('barrio', models.CharField(blank=True, max_length=255, null=True)),
                ('fraccion_censal', models.CharField(blank=True, max_length=255, null=True)),
                ('radio_censal', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_efector', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad_movil', models.IntegerField()),
            ],
            options={
                'db_table': 'efector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id_especie', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'especie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('tope_max', models.IntegerField(blank=True, null=True)),
                ('tope_min', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insumo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id_profesional', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('mail', models.CharField(blank=True, max_length=255, null=True)),
                ('matricula', models.CharField(max_length=15)),
                ('firma', models.TextField(null=True)),
            ],
            options={
                'db_table': 'profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProfesionalEfector',
            fields=[
                ('id_prof_efec', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'profesional_efector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id_raza', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tamaño', models.CharField(max_length=10)),
                ('limite_inf_altura_cm', models.IntegerField(blank=True, null=True)),
                ('limite_sup_altura_cm', models.IntegerField(blank=True, null=True)),
                ('limite_inf_peso_kg', models.IntegerField(blank=True, null=True)),
                ('limite_sup_peso_kg', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'raza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id_responsable', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('mail', models.CharField(blank=True, max_length=255, null=True)),
                ('firma', models.TextField(null=True)),
            ],
            options={
                'db_table': 'responsable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
    ]
