# Generated by Django 5.1.7 on 2025-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('regreso', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adopcion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdopcionFoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'adopcion_foto',
                'ordering': ['orden'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('dni', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('mail', models.EmailField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'candidato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'institucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InstitucionAnimal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingreso', models.DateField()),
                ('egreso', models.DateField(blank=True, null=True)),
                ('adopcion', models.BooleanField()),
                ('descripcion_adopcion', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'institucion_animal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeticionAdopcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada')], max_length=15)),
            ],
            options={
                'db_table': 'peticion_adopcion',
                'managed': False,
            },
        ),
    ]
